Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse("blogs:blog_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title
    
    

blog/forms.py
from django import forms
from blog.models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model= Post
        fields = ('title','text')
    
    def save_form(self, request, instance, form, change):
        user = request.user 
        instance = form.save(commit=False)
        if not change or not instance.author:
            instance.author = user
        instance.modified_by = user
        instance.save()
        form.save_m2m()
        return instance

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post
from django.utils import timezone
from blog.forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView )
from django.contrib import messages

# Create your views here.


class PostListView(ListView):
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'
    ordering = ['-created_date']
    model = Post



class PostDetailView(DetailView):
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'
    model = Post


def create_post(request):
    if request.method == 'POST':
        titulli = request.POST.get('title')
        permbajtja = request.POST.get('text')
        postim = Post(title=titulli, text=permbajtja, author=request.user)
        postim.save()
        messages.success(request, f'Postimi u krijua me sukses.')
        return redirect('blogs:post_list')
    return render(request, 'blog/create_post.html')

def delete_post(request, id):
    Post(id = id).delete()
    return redirect('blogs:post_list')

blog/templates/blog/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h1>Create Post</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <label for="">Titlle</label>
        <input type="text" class="form-control" name="title" placeholder="Titulli i postimit...">
        <label for="">Post</label>
        <textarea class="form-control" name="text" id="" cols="30" rows="10" placeholder="Permbajtja e postimit..."></textarea>
        <br>
        <button class="site-btn">create Post</button>
    </form>

</div>
<br>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row">
      <div class="col-lg-9">
          <h1>Post details</h1>
        <!-- blog post -->
        <div class="blog-post">
          <img src="img/blog/1.jpg" alt="">
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
            </div>
          </div>
          <p>{{ post.text|capfirst }} </p>
          <a href="/blog/" class="btn btn-dark">Go Back </a>
          {% if post.author == request.user %}
          <a href="/blog/{{ post.id }}/delete" class="btn btn-danger">Delete Post</a>
          {% endif %}
        </div>
      </div>
    </div>
</div>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}



<!-- Page  -->
<section class="blog-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-9">

        <a href="{% url 'blogs:create_post' %}" style="color: white;" class="site-btn">create Your Post</a>
        {% if posts %}
        {% for post in posts %}
        <!-- blog post -->
        <div class="blog-post">
          <img src="img/blog/1.jpg" alt="">
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
            </div>
          </div>
          <p>{{ post.text|capfirst }} </p>
          <a href="/blog/{{ post.id }}" class="btn btn-primary">Read More</a>
        </div>
        {% endfor %}
        {% else %}


        {% endif %}
        
  
      </div>
      <div class="col-lg-3 col-md-5 col-sm-9 sidebar">
        <div class="sb-widget-item">
          <form class="search-widget">
            <input type="text" placeholder="Search">
            <button><i class="fa fa-search"></i></button>
          </form>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Class</h4>
          <ul>
            <li><a href="#">Programing</a></li>
            <li><a href="#"></a>Social networks</li>
            <li><a href="#">news</a></li>
            <li><a href="#">Events</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Date</h4>
          <ul>
            <li><a href="#">February 2018</a></li>
            <li><a href="#">March 2018</a></li>
            <li><a href="#">April 2018</a></li>
            <li><a href="#">May 2018</a></li>
            <li><a href="#">June 2018</a></li>
          </ul>
        </div>
        <div class="sb-widget-item">
          <h4 class="sb-w-title">Hashtage</h4>
          <div class="tags">
            <a href="#">education</a>
            <a href="#">courses</a>
            <a href="#">development</a>
            <a href="#">design</a>
            <a href="#">on line courses</a>
            <a href="#">wp</a>
            <a href="#">html5</a>
            <a href="#">music</a>
          </div>
        </div>
        <div class="sb-widget-item">
          <div class="add">
            <a href="#"><img src="img/add.jpg" alt=""></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}