Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('memberships.urls',namespace='memberships')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, krijo_klase, krijo_lende, krijo_mesim

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', krijo_klase, name='krijo_klase'),
    path('krijo/lende', krijo_lende, name='krijo_lende'),
    path('krijo/mesim', krijo_mesim, name='krijo_mesim')
]

memberships/urls.py
from django.urls import path

from memberships.views import MembershipSelectView,PaymentView,UpdateTransactionRecords,CancelSubscription

app_name = 'memberships'

urlpatterns = [
    path('memberships/', MembershipSelectView.as_view(), name='select_membership'),
    path('payments/', PaymentView, name='payment'),
    path('update_transaction/<subscription_id>/update/', UpdateTransactionRecords, name='update_transaction'),
    path('cancel/', CancelSubscription, name='cancel')

]

courses/models.py
from django.db import models
from memberships.models import Membership
from django.contrib.auth.models import User
from django.urls import reverse

class Klasa(models.Model):
    titulli = models.CharField(max_length=150)
    pershkrimi = models.TextField(max_length= 200, null=True)
    imazhi = models.ImageField(upload_to='cat_images', default='cat_images/default.jpg')

    def __str__(self):
        return '{}'.format(self.titulli)

class Lendet(models.Model):
    krijues = models.ForeignKey(User,on_delete = models.CASCADE)
    slug = models.SlugField()
    titulli = models.CharField(max_length=30)
    klasa = models.ForeignKey(Klasa,on_delete=models.CASCADE)
    pershkrimi = models.TextField(max_length=400)
    krijuar_me = models.DateTimeField(auto_now=True)
    imazhi_lendes = models.ImageField(upload_to='kurs_images', default='default.jpg')

    def __str__(self):
        return self.titulli

    def get_absolute_url(self):
        return reverse("courses:course_detail", kwargs={"slug": self.slug})

    def get_courses_related_to_memberships(self):
        return self.courses.all()

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('pozicioni')




class Lesson(models.Model):
    slug = models.SlugField()
    titulli = models.CharField(max_length=30)
    lenda = models.ForeignKey(Lendet,on_delete=models.CASCADE)
    video_id = models.CharField(max_length=11)
    pozicioni = models.IntegerField()

    def __str__(self):
        return self.titulli

    def get_absolute_url(self):
        return reverse("courses:lesson_detail", kwargs={"course_slug": self.lenda.slug,'lesson_slug':self.slug})

courses/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Klasa, Lendet, Lesson



class KlasaForm(forms.ModelForm):
    class Meta:
        model = Klasa
        fields = '__all__'
        help_texts = {
            'titulli': 'Psh. Klasa 11 ose Klasa e Informatikes',
            'pershkrimi':'Vendos nje pershkrim te shkurte te klases',
            'imazhi':'Mund te vendosesh nje fotografi e klases ose mund te lihet bosh'
        }

class LendaForm(forms.ModelForm):
    class Meta:
        model = Lendet
        fields = ['krijues','slug', 'titulli', 'klasa', 'pershkrimi', 'imazhi_lendes']
        help_texts = {
            'titulli': 'Psh. Matematika, Gjeografi etj',
            'pershkrimi':'Vendos nje pershkrim te shkurte te lendes',
            'klasa':'Zhgjidhni klasen per te cilen do te krijoni lenden',
            'imazhi_lendes':'Mund te vendosesh nje fotografi e lendes ose mund te lihet bosh'
        }
        labels = {
            'titulli':'Titulli i lendes'
        }
        widgets = {'krijues': forms.HiddenInput(), 'slug': forms.HiddenInput()}


class MesimiForm(forms.ModelForm):
    class Meta:
        model = Lesson 
        fields = ['slug','titulli', 'lenda', 'video_id', 'pozicioni', ]
        help_texts = {
            'titulli':'Vendosni titullin e mesimit',
            'lenda':'Zgjidhni lenden per te cilen i perket ky mesim',
            'video_id':'Vendosni ID e videos nga Youtube te cilen do te ngarkoni (<a href="/media/youtube_help.png">ku mund ta gjej ID</a>)',
            'pozicioni':'Vendosni numrin e pozicionit ose radhen e mesimit '
        }
        widgets = {
            'slug': forms.HiddenInput()
        }

courses/views.py
import secrets
from django.shortcuts import render, redirect
from django.views.generic import TemplateView,ListView,DetailView,View
from courses.models import Lendet,Lesson,Klasa
from memberships.models import UserMembership
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import KlasaForm, LendaForm, MesimiForm
# Create your views here.

class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Klasa.objects.all()
        context['category'] = category
        return context

class AboutView(TemplateView):
    template_name = 'about.html'


class ContactView(TemplateView):
    template_name = 'contact.html'



def CourseListView(request, category):
    courses = Lendet.objects.filter(klasa=category)
    context = {
        'courses':courses
    }
    return render(request, 'courses/course_list.html', context)



class CourseDetailView(DetailView):
    context_object_name = 'course'
    template_name = 'courses/course_detail.html'
    model = Lendet


 
class LessonDetailView(View,LoginRequiredMixin):
    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(Lendet, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        context = {'lesson': lesson}
        return render(request, "courses/lesson_detail.html", context)


@login_required
def SearchView(request):
    if request.method == 'POST':
        kerko = request.POST.get('search')
        results = Lesson.objects.filter(titulli__contains=kerko)
        context = {
            'results':results
        }
        return render(request, 'courses/search_result.html', context)


@login_required
def krijo_klase(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Llogaria juaj nuk ka akses ne kete url vetem llogarite e mesuesve!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = KlasaForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Klasa juaj u krijua.')
            return redirect('courses:home')
    else:
        form = KlasaForm()
    context = {
        'form':form
    }
    return render(request, 'courses/krijo_klase.html', context)


@login_required
def krijo_lende(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Llogaria juaj nuk ka akses ne kete url vetem llogarite e mesuesve!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = LendaForm(request.POST)
        if form.is_valid():
            form.save()
            klasa = form.cleaned_data['klasa']
            slug = klasa.id
            messages.success(request, f'Lenda juaj u krijua.')
            return redirect('/courses/' + str(slug))
    else:
        form = LendaForm(initial={'krijues':request.user.id, 'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/krijo_lende.html', context)


@login_required
def krijo_mesim(request):
    if not request.user.profile.is_teacher == True:
        messages.error(request, f'Llogaria juaj nuk ka akses ne kete url vetem llogarite e mesuesve!')
        return redirect('courses:home')
    if request.method == 'POST':
        form = MesimiForm(request.POST)
        if form.is_valid():
            form.save()
            lenda = form.cleaned_data['lenda']
            slug = lenda.slug
            messages.success(request, f'Mesimi juaj u krijua.')
            return redirect('/courses/' + str(slug) )
    else:
        form = MesimiForm(initial={'slug':secrets.token_hex(nbytes=16)})
    context = {
        'form':form
    }
    return render(request, 'courses/krijo_mesim.html', context)


def view_404(request, exception):
    return render(request, '404.html')

def view_403(request, exception):
    return render(request, '403.html')

def view_500(request):
    return render(request, '500.html')

# def get(self,request,course_slug,lesson_slug,*args,**kwargs):
#
#     course_qs = Course.objects.filter(slug=course_slug)
#     if course_qs.exists():
#         course = course_qs.first()
#     lesson_qs = course.lessons.filter(slug=lesson_slug)
#     if lesson_qs.exists():
#         lesson = lesson_qs.first()
#     user_membership = UserMembership.objects.filter(user=request.user).first()
#     user_membership_type = user_membership.membership.membership_type
#
#     course_allowed_membership_type = course.allowed_memberships.all()
#     context = {'lessons':None}
#
#     if course_allowed_membership_type.filter(membership_type=user_membership_type).exists():
#         context = {'lesson':lesson}
#
#     return render(request,'courses/lesson_detail.html',context)

courses/templates/courses/course_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Home</a>
      <span>class</span>
      <span>teaching</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search for courses</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
            <input name="search" type="text" placeholder="Search for the course">
            <button type="submit" class="site-btn btn-dark">Search for the course</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->


<!-- single course section -->
<section class="single-course spad pb-0">
  <div class="container">
    <div class="course-meta-area">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          
          <h3>{{course.titulli|capfirst}}</h3>
          <div class="course-metas">
            <div class="course-meta">
              <div class="course-author">
                <h6>Mesues</h6>
                <p>{{course.krijues|capfirst}}, <span>Mesues</span></p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>class </h6>
                <p>{{course.klasa}}</p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Class description</h6>
                <p>{{course.pershkrimi}}</p>
              </div>
            </div>
            <div class="course-meta">
              <div class="cm-info">
                <h6>Number of lessons</h6>
                <p>{{ course.lessons|length }}</p>
              </div>
            </div>
          </div>
          <a href="/courses/{{ course.id }}" class="site-btn price-btn">Mbrapa</a>
          <a href="#vazhdo" class="site-btn buy-btn">Continue the Lesson</a>
        </div>
      </div>
    </div>
    <img src="img/courses/single.jpg" alt="" class="course-preview">
    <div class="row">
      <div class="col-lg-10 offset-lg-1 course-list">
        <div class="cl-item" id="lessons">
          <h4>Lessons in this class</h4>
          {% if course.lessons != None  %}
            {% for lesson in course.lessons %}
            <div data-aos="fade-right" >
              <h5 class="pb-3">teaching {{lesson.pozicioni}} <a id="vazhdo" href="{{ lesson.get_absolute_url }}#video"><span class="pl-4">{{lesson.titulli}}</span></a></h5>
            </div>
            {% endfor %}
          {% endif %}
          {% if course.lessons|length == 0 %}
          <div class="alert alert-danger">There are no lessons for this class yet!</div>
          {% endif %} 
        </div>
      </div>
    </div>
  </div>
</section>



{% endblock %}

courses/templates/courses/course_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/1.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Society</a>
      <span>Course</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search for the course</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
            <input name="search" type="text" placeholder="Search for the course">
            <button type="submit" class="site-btn btn-dark">Search for the course</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->

<div class="course-warp">
  <ul class="course-filter controls">
    <li class="control active" data-filter="all">All course</li>
  </ul>
<div class="featured-courses">

      <div class="featured-course course-item">
        <div class="row">
          {% for course in courses %}
          <div class="col-lg-6 pb-4">
            <div class="course-info">
              <div class="course-text">
                <h5>{{course.klasa}}</h5>
                <a href="{% url 'courses:course_detail' course.slug %}"><h3 class="">{{course.titulli|capfirst}}</h3></a>
                <p>{{course.pershkrimi}}</p>
                <div class="students"><a href="{% url 'courses:course_detail' course.slug %}" class="btn btn-primary">class lessons</a></div>
              </div>
              <div class="course-author">
                <div class="ca-pic set-bg" data-setbg="{{ request.user.profile.profile_pic.url }}"></div>
                <p>created by {{course.krijues|capfirst}}, <span>Teacher</span></p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

courses/templates/courses/krijo_klase.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>create</h1>
        <form method="post" action="/krijo/klase" enctype='multipart/form-data'>{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">Create Class</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/krijo_lende.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1> create</h1>
        <form method="post" action="/krijo/lende" enctype='multipart/form-data'>{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">
                Create stuff</button>
        </form>
</div>
{% endblock %}

courses/templates/courses/krijo_mesim.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Create middle</h1>
        <form method="post" action="/krijo/mesim">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn mb-4 btn-primary">
                Create stuff </button>
        </form>
</div>
{% endblock %}

courses/templates/courses/lesson_detail.html
{% extends 'base.html' %}
{% load static %}
{% block post_detail_link %}

{% endblock %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">society</a>
      <span>class</span>
      <span>Teacher</span>
      <span>Video </span>
    </div>
  </div>
</div>
  <!-- {% if lesson is not None %}
	<li class="form-control"><a  href="{{ lesson.course.get_absolute_url }}">Mesimi : {{ lesson.course.titulli }}</a></li>
	<li class="form-control">Title : {{ lesson.titulli }}</li>
  {% endif %} -->

<!-- Page info end -->

	<div  id="video" class='container'>
		<div class="alert alert-info" role="alert">
			here is the video for the lecture 
		  </div>
		<h1>{{ lesson.titulli }}</h1>
		<div class='row'>
			<div class='col-sm-12 col-md-12'>
				{% if lesson is not None %}

				<iframe id="video" width="100%" height="450px" src="https://www.youtube-nocookie.com/embed/{{ lesson.video_id }}?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

				<div class="text-center">
				<a href="javascript:history.back()" class="mb-5 mt-2 btn btn-primary">Back to lessons</a>
				</div>

				{% else %}
				<!-- <h3>Upgrade membership</h3>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select_membership' %}"><button class="btn btn-warning">Upgrade Membership</button></a>
				<hr> -->
				{% endif %}
			</div>
		</div>
	</div>

{% endblock content %}

courses/templates/courses/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-top-bg.jpg'%}">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <br><br>
        <br>
        <br><br>
        <br>
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="Kerko kursin">
          <button type="submit" class="site-btn">Search course</button>
        </form>
      </div>
    </div>
  </div>
</section>
<div class="container">
    <h1 class=" mt-2 text-center">
      Search results{{ results|length }}:</h1>
    <div class="row course-items-area">
        <!-- course -->
        {% if results %}
        {% for lesson in results %}
        <div class="mix col-lg-4 col-md-4 col-sm-6 finance">
          <div class="course-item">
              <a href="/courses/{{ lesson.lenda.slug }}/">
            <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
              <iframe width="100%" height="290" src="https://www.youtube.com/embed/{{ lesson.video_id }}?controls=0"  frameborder="0" controls allowfullscreen></iframe>  
              
            </div>
            <div class="course-info">
              <div class="course-text">
                <h5>{{ lesson.titulli }}</h5>
                <p>{{ lesson.lenda }}</p>
                <div class="students">class 10</div>
              </div>
            </a>
            </div>
          </div>
        </div>
        {% endfor %}
        
        {% else %}
        <div class="text-center">
            <h4>
              There are no results</h4>
        </div>
        {% endif %}
        <!-- course -->
      </div>
</div>



{% endblock %}